# Generated by Django 4.1.7 on 2023-03-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_summmary',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
