# Generated by Django 4.1.7 on 2023-03-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_book_book_summmary_book_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_summmary',
        ),
        migrations.AddField(
            model_name='book',
            name='book_summary',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
