# Generated by Django 4.1.7 on 2023-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_remove_book_book_summmary_book_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
